### ISSUE TITLE
conda packaging?

### ISSUE THREAD

**Issue by whophil** [mdolab/CMPLXFOIL#15]
# Description of feature

Package for conda-forge. Thoughts @nwu63 ?

We (my company) also has some bugfixes and features we'd be happy to port back onto this project if we can get a conda-forge package.

We also have a working recipe - very minimal for this project, but just letting you know that we've done the legwork and there is no issue in building/packaging.

# Potential solution

**Comment by nwu63** [comment]
I think this would be a nice addition. While very few in the lab actually use conda, I'm sure others would benefit from this, and of course we'd be happy to take contributions on bugfixes etc. as well. Related to this, does #14 affect anything here? The build process should be unchanged but the Python wrapper is overhauled significantly.

**Comment by whophil** [comment]
@nwu63 I took a quick glance at that PR and have a few thoughts related to packaging. I will add some comments there. Thanks!

**Comment by whophil** [comment]
@eytanadler @nwu63 Thinking a bit more about this, I don't know that having a conda package for CMPLXFOIL would actually be that useful _today_. Since all the f2py work is handled correctly with `pip install` and because there aren't really any library dependencies that conda would be helpful to install. (Contrast with `pyoptsparse`, whose compilation requires SWIG, BLAS, LAPACK, IPOPT, ...)

I'm happy to close this issue on my side, unless you prefer to leave it open.

**Comment by bernardopacini** [comment]
Thanks for reaching out about this! As @nwu63 mentioned, besides the possible packaging solutions we would be very interested in your bug fixes and updates. How can we help with this? Please feel free to leave this issue open as a place to discuss those changes if you would like, or we can start a new issue specifically for those changes. Let us know what support we can provide from our side.

**Comment by whophil** [comment]
I'll open a new issue to discuss other changes. Thanks!
