### ISSUE TITLE
no convergence behaviour

### ISSUE THREAD

**Issue by pl96andy** [mdolab/CMPLXFOIL#24]
## Description

When trying to calculate airfoil and xfoil is failing to converge, i receive error that airfoil is failing to converge and program terminates execution
I guess there is no much use of it because after receiving such information i wish to continue execution of my program

### Current behavior
As an output i am receiving:
`
 Sharp trailing edge

 Sharp trailing edge
 Paneling convergence failed.  Continuing anyway...

 Sharp trailing edge
+----------------------------------------------------------------------+
|  Switching to Aero Problem: fc                                       |
+----------------------------------------------------------------------+

 CPCALC: Local speed too large. Compressibility corrections invalid.

 CPCALC: Local speed too large. Compressibility corrections invalid.

Process finished with exit code 0
`

### Code versions

- Operating System: Ubuntu 22.04.3 LTS
- Python: Python 3.11.5 in anaconda

**Comment by A-CGray** [comment]
This looks like an XFoil issue, not something specific to CMPLXFOIL. Try looking up what kind of might cause the paneling to fail in XFoil

**Comment by pl96andy** [comment]
of course cause incorrect airfoil geometry but problem is that code does not only return error but it also terminates process
my workaround is to call CMPLXFOIL in separate child process for xfoil to kill its own process not main program
i just consider necessity of such workaround is strange
